{% set name = "gradio-client" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gradio_client-{{ version }}.tar.gz
  sha256: fe8201b915a9018a8681a33b236b8cce702f5ccb38d5eeb91a198dbb05c14991

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - hatch-requirements-txt
    - hatch-fancy-pypi-readme >=22.5.0
    - pip
  run:
    - python >=3.8
    - fsspec
    - httpx >=0.24.1
    - huggingface_hub >=0.19.3
    - packaging
    - typing_extensions ~=4.0
    - websockets >=10.0,<12.0

test:
  imports:
    - gradio_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/gradio-client/
  dev_url: https://github.com/gradio-app/gradio
  summary: Python library for easily interacting with trained machine learning models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sclare87
